networks:
  cluster:
    external: true
services:
  node1:
    image: node
    container_name: node1
    volumes:
      - /home/irina/UTM/SEM5/PR/LAB3/config_Node1:/app/config
    networks:
      - cluster

    restart: always
    ports:
      - "8080:8080"
      - "9080:9080"
    expose:
      - "8080"
      - "9080"

  node2:
    image: node
    container_name: node2
    volumes:
      - /home/irina/UTM/SEM5/PR/LAB3/config_Node2:/app/config
    networks:
      - cluster
    restart: always
    ports:
      - "8082:8080"
      - "9082:9080"
    expose:
      - "8082"
      - "9082"

  node3:
    image: node
    container_name: node3
    volumes:
      - /home/irina/UTM/SEM5/PR/LAB3/config_Node3:/app/config

    networks:
      - cluster
    restart: always
    ports:
      - "8084:8080"
      - "9084:9080"
    expose:
      - "8084"
      - "9084"
